export const Wgt_Statewise_Data = [
    {
      id: 1,
      state: "Delhi",
      bg: "w3-red", 
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  
    {
      id: 2,
      state: "Haryana",
      bg: "w3-red", 
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    }, 
    {
      id: 3,
      state: "Punjab",
      bg: "w3-red", 
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    }, 

    {
      id: 4,
      state: "Himachal",
      bg: "w3-red", 
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  
    {
      id: 5,
      state: "J&K",
      bg: "w3-red", 
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  
    {
      id: 6,
      state: "Uttrakhand",
      bg: "w3-red", 
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  
    {
      id: 7,
      state: "Uttar Pradesh",
      bg: "w3-red", 
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  
    {
      id: 8,
      state: "Rajasthan",
      bg: "w3-red", 
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    }, 
  ];