export const Wgt_Sum_Zone_Wise_Data = {
  id: 1,
  summ_entity_id: 1,
  summ_entity_name: 1,
  summ_lly_fy: "21-22",
  summ_lly_sale_value: "480",
  summ_ly_fy: "22-23",
  summ_ly_sale_value: "600",
  summ_cy_fy: "23-24",
  summ_cy_target_v1_value: "876",
  summ_cy_target_v2_value: "876",
  summ_cy_target_v1_percentage: "46",
  summ_cy_target_v2_percentage: "46",
  summ_cy_sale_ytd_value: "60",
  summ_cy_sale_ytd_percentage: "12",
};

export const Wgt_Sum_Zone_Wise_Chart_Data = [
  {
    id: 1,
    entity_id: 1,
    entity_name: "YTD",
    currentMonth: "Aug",
    currentMonthTarget: "65 Cr",
    percentage: "12",
  },
  {
    id: 1,
    entity_id: 1,
    entity_name: "Plan",
    currentMonth: "Aug",
    currentMonthTarget: "65 Cr",
    percentage: "",
  },
];

export const Wgt_Statewise_Data = [
  {
    id: 1,
    state: "Delhi",
    bg: "w3-red",
    ly: "100",
    target: "126",
    target_percentage: "26",
    achieved: "60",
    achieved_percentage: "12",
  },
  {
    id: 2,
    state: "Haryana",
    bg: "w3-red",
    ly: "100",
    target: "126",
    target_percentage: "26",
    achieved: "60",
    achieved_percentage: "12",
  },
  {
    id: 3,
    state: "Punjab",
    bg: "w3-red",
    ly: "100",
    target: "126",
    target_percentage: "26",
    achieved: "60",
    achieved_percentage: "12",
  },

  {
    id: 4,
    state: "Himachal",
    bg: "w3-red",
    ly: "100",
    target: "126",
    target_percentage: "26",
    achieved: "60",
    achieved_percentage: "12",
  },
  {
    id: 5,
    state: "J&K",
    bg: "w3-red",
    ly: "100",
    target: "126",
    target_percentage: "26",
    achieved: "60",
    achieved_percentage: "12",
  },
  {
    id: 6,
    state: "Uttrakhand",
    bg: "w3-red",
    ly: "100",
    target: "126",
    target_percentage: "26",
    achieved: "60",
    achieved_percentage: "12",
  },
  {
    id: 7,
    state: "Uttar Pradesh",
    bg: "w3-red",
    ly: "100",
    target: "126",
    target_percentage: "26",
    achieved: "60",
    achieved_percentage: "12",
  },
  {
    id: 8,
    state: "Rajasthan",
    bg: "w3-red",
    ly: "100",
    target: "126",
    target_percentage: "26",
    achieved: "60",
    achieved_percentage: "12",
  },
];
