export const Wgt_Zone_Data = [
    {
      id: 1,
      title: "North",
      bg: "w3-red",
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },

   {
      id: 2,
      title: "South",
      bg: "w3-indigo",
      ly: "90",
      target: "110",
      target_percentage: "26",
      achieved: "26",
      achieved_percentage: "12",
    },
    {
      id: 3,
      title: "East",
      bg: "w3-teal",
      ly: "110",
      target: "130",
      target_percentage: "26",
      achieved: "40",
      achieved_percentage: "12",
    },{
      id: 4,
      title: "West",
      bg: "w3-orange",
      ly: "130",
      target: "160",
      target_percentage: "26",
      achieved: "80",
      achieved_percentage: "12",
    },
    ,{
      id: 5,
      title: "Other",
      bg: "w3-orange",
      ly: "130",
      target: "160",
      target_percentage: "26",
      achieved: "80",
      achieved_percentage: "12",
    },
  ];