export const Wgt_Marketsector_Data = [
    {
      id: 1,
      marketsector_code: "1000001",
      marketsector_name: "ENAMELS", 
      marketsector_target_value: "24",
      marketsector_target_percentage: "24",
      marketsector_target_ytd_value: "24",
      marketsector_target_ytd_percentage: "24",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    }, 
    {
      id: 2,
      marketsector_code: "1000002",
      marketsector_name: "Interior Emulsion", 
      marketsector_target_value: "34",
      marketsector_target_percentage: "34",
      marketsector_target_ytd_value: "34",
      marketsector_target_ytd_percentage: "34",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    }, 

    {
      id: 3,
      marketsector_code: "1000003",
      marketsector_name: "Primers", 
      marketsector_target_value: "14",
      marketsector_target_percentage: "14",
      marketsector_target_ytd_value: "14",
      marketsector_target_ytd_percentage: "14",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },  

    {
      id: 4,
      marketsector_code: "1000004",
      marketsector_name: "Exterior Emulsion", 
      marketsector_target_value: "44",
      marketsector_target_percentage: "44",
      marketsector_target_ytd_value: "44",
      marketsector_target_ytd_percentage: "44",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },    

    {
      id: 5,
      marketsector_code: "1000005",
      marketsector_name: "Water Proofing", 
      marketsector_target_value: "34",
      marketsector_target_percentage: "34",
      marketsector_target_ytd_value: "34",
      marketsector_target_ytd_percentage: "34",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },    

    {
      id: 6,
      marketsector_code: "1000006",
      marketsector_name: "Dry Colours", 
      marketsector_target_value: "14",
      marketsector_target_percentage: "14",
      marketsector_target_ytd_value: "14",
      marketsector_target_ytd_percentage: "14",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },    

    {
      id: 7,
      marketsector_code: "1000007",
      marketsector_name: "Acrlylic Distemper", 
      marketsector_target_value: "64",
      marketsector_target_percentage: "64",
      marketsector_target_ytd_value: "64",
      marketsector_target_ytd_percentage: "64",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },    

    {
      id: 8,
      marketsector_code: "1000008",
      marketsector_name: "Other Decorative", 
      marketsector_target_value: "44",
      marketsector_target_percentage: "44",
      marketsector_target_ytd_value: "44",
      marketsector_target_ytd_percentage: "44",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },       

    {
      id: 9,
      marketsector_code: "1000009",
      marketsector_name: "Aluminium Paints", 
      marketsector_target_value: "14",
      marketsector_target_percentage: "14",
      marketsector_target_ytd_value: "14",
      marketsector_target_ytd_percentage: "14",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },    
    {
      id: 10,
      marketsector_code: "10000010",
      marketsector_name: "Putty", 
      marketsector_target_value: "7",
      marketsector_target_percentage: "7",
      marketsector_target_ytd_value: "7",
      marketsector_target_ytd_percentage: "7",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },   
    {
      id: 11,
      marketsector_code: "10000011",
      marketsector_name: "Stainer", 
      marketsector_target_value: "17",
      marketsector_target_percentage: "17",
      marketsector_target_ytd_value: "17",
      marketsector_target_ytd_percentage: "17",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },    
    {
      id: 12,
      marketsector_code: "10000012",
      marketsector_name: "Wood Finish", 
      marketsector_target_value: "27",
      marketsector_target_percentage: "27",
      marketsector_target_ytd_value: "27",
      marketsector_target_ytd_percentage: "27",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },   
    {
      id: 13,
      marketsector_code: "10000013",
      marketsector_name: "Warnishes", 
      marketsector_target_value: "2",
      marketsector_target_percentage: "2",
      marketsector_target_ytd_value: "2",
      marketsector_target_ytd_percentage: "2",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },  
    {
      id: 14,
      marketsector_code: "10000014",
      marketsector_name: "Textures", 
      marketsector_target_value: "17",
      marketsector_target_percentage: "17",
      marketsector_target_ytd_value: "17",
      marketsector_target_ytd_percentage: "17",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },    
    {
      id: 15,
      marketsector_code: "10000015",
      marketsector_name: "Industrial", 
      marketsector_target_value: "15",
      marketsector_target_percentage: "15",
      marketsector_target_ytd_value: "15",
      marketsector_target_ytd_percentage: "15",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },    
    {
      id: 16,
      marketsector_code: "10000016",
      marketsector_name: "Colourspace Colorant", 
      marketsector_target_value: "11",
      marketsector_target_percentage: "11",
      marketsector_target_ytd_value: "11",
      marketsector_target_ytd_percentage: "11",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },     
    {
      id: 17,
      marketsector_code: "10000017",
      marketsector_name: "Healthcare", 
      marketsector_target_value: "7",
      marketsector_target_percentage: "7",
      marketsector_target_ytd_value: "7",
      marketsector_target_ytd_percentage: "7",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },     
    {
      id: 18,
      marketsector_code: "10000017",
      marketsector_name: "Cement Paint", 
      marketsector_target_value: "9",
      marketsector_target_percentage: "9",
      marketsector_target_ytd_value: "9",
      marketsector_target_ytd_percentage: "9",
      company_target_value: "100",
      company_target_fy: "FY-23-24",
      company_target_fy_v: "v1",
    },   
  ];