export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const SHOW_TOAST = "SHOW_TOAST";
export const AUTH_DATA = "AUTH_DATA";

export const API_NAT_SUM_WIDGET_REQ = "API_NAT_SUM_WIDGET_REQ";
export const API_NAT_SUM_WIDGET_SUCCESS = "API_NAT_SUM_WIDGET_SUCCESS";

export const API_NAT_ZONE_WIDGET = "API_NAT_ZONE_WIDGET";
export const API_NAT_MARKET_WIDGET = "API_NAT_MARKET_WIDGET";

export const API_TARRITORY_SALES_REQ = "API_TARRITORY_SALES_REQ";
export const API_TARRITORY_SALES_SUCCESS = "API_TARRITORY_SALES_SUCCESS";

export const API_DEPOT_SALES_PLAN_SUCCESS = "API_DEPOT_SALES_PLAN_SUCCESS";

export const API_SUMMARY_SUCCESS = "API_SUMMARY_SUCCESS";
export const API_MONTH_WISE_SALES_SUCCESS = "API_MONTH_WISE_SALES_SUCCESS";


